project:
  type: website
  output-dir: _site
  resources:
    - CNAME

website:
  title: "SheafofThoughts"

  comments:
    giscus:
      repo: "sheafofthoughts/sheafofthoughtsblog"
      repo-id: "R_kgDOQmlT5A"
      category: "Announcements"
      category-id: "DIC_kwDOQmlT5M4C0SVZ"
      mapping: "pathname"
      reactions-enabled: true
      input-position: "bottom"
      theme: "preferred_color_scheme"

  site-url: https://sheafofthoughts.org
  navbar:
    left:
      - href: index.qmd
        text: Recent Posts
    right:
      - href: about.qmd
        text: About
      - href: privacy.qmd
        text: Privacy

format:
  html:
    include-in-header: 
      - bing-verify.html
    theme:
      light: flatly
      dark: darkly

    toc: true
    toc-depth: 3
    math: mathjax
    css: styles.css
  pdf:
    documentclass: scrartcl
    include-in-header: pdf-header.tex

filters:
  - tikz

