project:
  type: website
  output-dir: _site
  resources:
    - CNAME

website:
  title: "SheafofThoughts"
  site-url: https://sheafofthoughts.org
  navbar:
    left:
      - href: index.qmd
        text: Recent Posts
    right:
      - href: about.qmd
        text: About

format:
  html:
    theme:
      light: flatly
      dark: darkly

    toc: true
    toc-depth: 3
    math: mathjax
    css: styles.css
  pdf:
    documentclass: scrartcl
    include-in-header: pdf-header.tex

filters:
  - tikz

